/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package modelCheckCTL.controller.ctl.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int IMPLIES = 8;
  /** RegularExpression Id. */
  int AX = 9;
  /** RegularExpression Id. */
  int AF = 10;
  /** RegularExpression Id. */
  int AG = 11;
  /** RegularExpression Id. */
  int EX = 12;
  /** RegularExpression Id. */
  int EF = 13;
  /** RegularExpression Id. */
  int EG = 14;
  /** RegularExpression Id. */
  int A = 15;
  /** RegularExpression Id. */
  int E = 16;
  /** RegularExpression Id. */
  int U = 17;
  /** RegularExpression Id. */
  int LPAREN = 18;
  /** RegularExpression Id. */
  int RPAREN = 19;
  /** RegularExpression Id. */
  int ATOM = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"->\"",
    "\"AX\"",
    "\"AF\"",
    "\"AG\"",
    "\"EX\"",
    "\"EF\"",
    "\"EG\"",
    "\"A\"",
    "\"E\"",
    "\"U\"",
    "\"(\"",
    "\")\"",
    "<ATOM>",
  };

}
